O_epsilon = 0.0000001
INFINITE_FLOW_RATE = 100000000
EXPONENTIAL_DECAY = 0
EXPONENTIAL_DECAY_LEN = 1
EXPONENTIAL_LEN = 1
RANDOM = 2
UNIFORM = 3
APPROX = "approx({})"
APPROX_MCF = "approx({})_mcf"
APPROX_BET = "approx({})_bet"
APPROX_BET_MCF = "approx({})_bet({})_mcf"
APPROX_BET_MCF_BIASED = "approx({})_bet({})_biased_mcf"
SWAN = "SWAN"
DANNA = "Danna"
NEW_APPROX = "Geometric Binner"
ONE_WATERFILLING = "1-waterfilling"
